### ISSUE TITLE
TypeError: resources.ProjectMemberships is not a constructor

### ISSUE THREAD

**Issue by andrelung** [Asana/node-asana#160]
Not sure, if this is related to the oauth_webserver.js example or the client.js, but I keep getting this error when trying to get the oauth working:
` ~/dev/node-asana-master/examples/oauth/webserver
$ node oauth_webserver.js
Listening on port 5000
TypeError: resources.ProjectMemberships is not a constructor
    at new Client (/Users/al/dev/node-asana-master/lib/client.js:49:29)
    at Function.Client.create (/Users/al/dev/node-asana-master/lib/client.js:179:10)
    at createClient (/Users/al/dev/node-asana-master/examples/oauth/webserver/oauth_webserver.js:29:23)
    at /Users/al/dev/node-asana-master/examples/oauth/webserver/oauth_webserver.js:41:16
    at Layer.handle [as handle_request] (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/layer.js:95:5)
    at /Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:317:13)
    at /Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/al/dev/node-asana-master/examples/oauth/webserver/node_modules/express/lib/router/index.js:335:12)`

Can someone help?

**Comment by joetrollo** [comment]
Sorry about this issue, it seems that an individual automated test failed but Travis still marked the suite as passing, which is how this bug was merged in. It should be fixed in the [latest release](https://github.com/Asana/node-asana/releases/tag/v0.16.0), though. Can you confirm whether the problem persists?
