### ISSUE TITLE
CORS request rejected v0.7.9

### ISSUE THREAD

**Issue by keenanpayne** [Asana/node-asana#72]
```
XMLHttpRequest cannot load https://app.asana.com/api/1.0/users/me. Request header field X-Asana-Client-Lib is not allowed by Access-Control-Allow-Headers.

asana.js:4238 Unhandled rejection Error: CORS request rejected: https://app.asana.com/api/1.0/users/me
    at on_response (http://localhost/wp-content/themes/asana-2014/src/js/lib/asana.js:8589:22)
    at XMLHttpRequest.on_state_change (http://localhost/wp-content/themes/asana-2014/src/js/lib/asana.js:8572:7)
```

**Comment by raysaagar** [comment]
we've made a fix that should unbreak the library.
