### ISSUE TITLE
Cryptic error when using OAuth refresh token

### ISSUE THREAD

**Issue by super-cache-money** [Asana/node-asana#97]
I'm trying to use a `refresh_token` to authenticate using OAuth. Here's what I've got:

```
var asana = require('asana');
var client = asana.Client.create({
    clientId : myClientId,
    clientSecret : myClientSecret

});

client.useOauth({
    credentials : {
        refresh_token: myRefreshToken
    }
});

client.users.me().then(function(me) {
    console.log('Hello ' + me.name);
});
```

Unfortunately, this throws the following error:

```
> Unhandled rejection TypeError: Cannot read property 'hasOwnProperty' of null
    at appendFormValue (/Users/me/project/node_modules/asana/node_modules/request/request.js:330:16)
    at Request.init (/Users/me/project/node_modules/asana/node_modules/request/request.js:344:11)
    at new Request (/Users/me/project/node_modules/asana/node_modules/request/request.js:140:8)
    at request (/Users/me/project/node_modules/asana/node_modules/request/index.js:55:10)
    at /Users/me/project/node_modules/asana/lib/auth/app.js:13:5
    at tryCatcher (/Users/me/project/node_modules/asana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/me/project/node_modules/asana/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/me/project/node_modules/asana/node_modules/bluebird/js/main/promise.js:70:37)
    at doRequest (/Users/me/project/node_modules/asana/lib/auth/app.js:12:10)
    at App.accessTokenFromRefreshToken (/Users/me/project/node_modules/asana/lib/auth/app.js:131:10)
    at OauthAuthenticator.refreshCredentials (/Users/me/project/node_modules/asana/lib/auth/oauth_authenticator.js:95:34)
    at Dispatcher.maybeReauthorize [as handleUnauthorized] (/Users/me/project/node_modules/asana/lib/dispatcher.js:82:29)
    at Request._callback (/Users/me/project/node_modules/asana/lib/dispatcher.js:153:33)
    at Request.self.callback (/Users/me/project/node_modules/asana/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/me/project/node_modules/asana/node_modules/request/request.js:1063:14)
```

What's happening here? I'm pretty sure my auth details are correct, and the above code works fine when I supply an  `access_token` instead.

**Comment by super-cache-money** [comment]
Figured it out. It's because I didn't specifiy `requestUri` when creating the client. Would be useful if a more descriptive error message was displayed. I assumed I could leave it out because of [https://github.com/Asana/node-asana/blob/master/examples/oauth/script/oauth_script.js](this example).
